### ISSUE TITLE
Can't run sample JSON.

### ISSUE THREAD

**Issue by takuoka** [PavelLaptev/JSON-to-Figma#16]
I tried to correct sample, but It don't work.

![image](https://user-images.githubusercontent.com/2075801/93844493-4640aa80-fcd8-11ea-8edd-6be969c5b550.png)

↓

![image](https://user-images.githubusercontent.com/2075801/93844498-4a6cc800-fcd8-11ea-9b03-65a687d14f0e.png)

**Comment by PavelLaptev** [comment]
@entotsu Hi!
The reason that your JSON syntax is not valid and the code editor is highlighting it to you. 
Your code is an JS object not a JSON — https://medium.com/@alifabdullah/never-confuse-json-and-javascript-object-ever-again-7c32f4c071ad
"JSON is basically the “String” version of JavaScript Object. Its simply a text-based data format and single quote is not allowed for JSON.'
All you need to do here is make a few fixes:
![image](https://user-images.githubusercontent.com/18498712/93846184-a832ed00-fca3-11ea-8433-3980a4660b5b.png)

**Comment by takuoka** [comment]
Thank you @PavelLaptev .

but,, Is README 's grammer invalid?

--- 

![image](https://user-images.githubusercontent.com/2075801/93846525-3d9fa280-fcdf-11ea-8444-747e036327b4.png)

**Comment by takuoka** [comment]
And,, It's still not working... 🤔 
![image](https://user-images.githubusercontent.com/2075801/93846716-ca4a6080-fcdf-11ea-910f-ea6ed01f6317.png)

**Comment by PavelLaptev** [comment]
@entotsu my bad. Thank you. I fixed the `README`. In your example it doesn't work because of the `commented` line below — JSON doesn’t accept them. If you delete it, JSON should pass successfully
![image](https://user-images.githubusercontent.com/18498712/93850979-8ccddf00-fcaf-11ea-9ed7-ce3e6e9f82e0.png)

Please, check out examples here —  https://github.com/PavelLaptev/JSON-to-Figma/tree/master/json-test-files
